export const QUERY_KEY = {
  WATCH_LIST: "WATCH_LIST",
  RECENT_LIST: "RECENT_LIST",
  CONTINUE_WATCHING: "CONTINUE_WATCHING",
  GENRES: "GENRES",
  MOVIES_BY_GENRES: "MOVIES_BY_GENRES",
  MOVIES_DETAIL: "MOVIES_DETAIL",
  TOP_RATED: "TOP_RATED",
  RANDOM_MOVIES: "RANDOM_MOVIES",
  ME: "ME",
  RATING: "RATING",
};
